// examples/web/interface/src/App.svelte
<style>
	.app {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	.form {
		display: flex;
		flex-direction: column;

		color: white;
		background-color: blue;
		margin: 8px;
		padding: 8px;
		padding-top: 100px;
		transform: translate(0px, -100px);
		border-radius: 8px;
		box-shadow: #555555 4px 4px 4px;
	}

	.form .row {
		display: flex;
		flex-direction: row;
		justify-content: flex-end;

		margin: 0px 4px;
	}
</style>

<script>
	import Input from './Input.svelte'
	import Display from './Display.svelte'
	
	let params = new Map()
</script>

<div class='app'>
	<div class='form'>
		<div class='row'>
			<Input bind:value={params['src']} label='Depth Map' type='text' />
			<Input bind:value={params['pat']} label='Pattern' type='text' />
			<Input bind:value={params['seed']} label='Seed' type='number' defaultValue={0} />
			<Input bind:value={params['partsize']} label='Part Size' type='number' defaultValue={100} min={0} max={500} />
			<Input bind:value={params['depth']} label='Max Depth' type='number' defaultValue={40} min={0} max={50} />
			<Input bind:value={params['sym']} label='Symmetric Random Generation' type='checkbox' />
			<Input bind:value={params['inverse']} label='Inverse' type='checkbox' />
			<Input bind:value={params['flat']} label='Flat' type='checkbox' />
		</div>
	</div>

	<Display {params} />
</div>

// examples/web/src/App.tsx
import Input, { useInputs } from "./Input.tsx";
import Display from "./Display.tsx";
import type { Params } from "./Display.tsx";

export function App() {
  const [params, inputs] = useInputs();

  return (
    <div className="flex flex-col items-center">
      <div className="flex flex-col bg-base-300 m-4 p-4 pt-25 transform-[translate(0px,-100px)] rounded-lg shadow-lg">
        <div className="flex flex-row justify-end mx-0 my-2">
          <Input label="Depth Map" {...inputs.text("src")} />
          <Input label="Pattern" {...inputs.text("pat")} />
          <Input label="Seed" {...inputs.number("seed")} />
          <Input label="Part Size" {...inputs.range("partsize", 0, 500, 100)} />
          <Input label="Max Depth" {...inputs.range("depth", 0, 50, 40)} />
          <Input
            label="Symmetric Random Generation"
            {...inputs.checkbox("sym")}
          />
          <Input label="Inverse" {...inputs.checkbox("inverse")} />
          <Input label="Flat" {...inputs.checkbox("flat")} />
        </div>
      </div>

      <Display params={params as Params} />
    </div>
  );
}

export default App;
